language: node_js
sudo: false
node_js:
- '12'
cache:
  directories:
  - node_modules
install:
- npm install
before_script: true
script:
- npm test
- echo "Salut"
- "./node_modules/.bin/jshint"
- "./node_modules/.bin/retire"
after_script: true
  - "./node_modules/.bin/twly"
  if: branch = dev
deploy:
  provider: heroku
  api_key:
    secure: NeRHImm+dO6wmSd+XG3gAu/gITBGqVCTrSE9F9chQYpFvpEiWa9vTNu6AVwtfqpg+w130vOsU9ujGz4kbwb/WESXt61/5jesPgnRzogw+07CdotjDIjoS+9BVj07iKZjMECCznNgqeG+P7kAK5qv8ZSlfgcCaGZeLMWfQf03BRCu4ImM9/rP1QgwQjSle9cYqdap2kQ4NZJZ5Jb4IrjmR1pcDZe904Q0mVo1NlpBVm00IfghATCvAxy0fCzXXbPDeEOzJArkTCh/hPHwDcn1fBLRcIxVVZ+vIRxZD7fRRVCUpzn4AB/mtQ3pogYYpqpJOkf3+mSlhU4dO+imZeEcRg2n/4BaTpKAOkG+3ywDmNGYm6Sy5prg8hNBjIPs/qeOV9xeyG/9g4Z+yFSqVzdPuHfbF8YMJOBs8r6roKZjhKUk9tHpsKiTvrB1dEGxSLwXqaDlBPyTnFl1Q/zieJR1e2/GXME4RepUOZ8ez8QlNosTy5m03TXAsKf8gBcqfuHgYIeXV7rLy6iHyBSlE1ZxL3NcAVg4okts34Gf9CCuLVTB56V2yVR1JULjQWH7HXAJg3BKG88hd+zBmOyumy1hrkR4zFDIsZOYusgpQCYnUgVPFdD9i1GICWG4WEbNTBLpiAMZeMPr99ujdNQIt/9/mgl4i2Psd6ZAVRxg8l1VSE0=
  app: node-travis-test
  on:
    repo: julien-lav/jsapp_travis
    branch: dev
